export default {
  automotive: require('./automotive.jpg'),
  fragrances: require('./fragrances.jpg'),
  furniture: require('./furniture.jpg'),
  groceries: require('./groceries.jpg'),
  'home-decoration': require('./home-decoration.jpg'),
  laptops: require('./laptops.jpg'),
  lighting: require('./lighting.jpg'),
  'mens-shirts': require('./mens-shirts.jpg'),
  'mens-shoes': require('./mens-shoes.jpg'),
  'mens-watches': require('./mens-watches.jpg'),
  motorcycle: require('./motorcycle.jpg'),
  skincare: require('./skincare.jpg'),
  smartphones: require('./smartphones.jpg'),
  sunglasses: require('./sunglasses.jpg'),
  tops: require('./tops.jpg'),
  'womens-bags': require('./womens-bags.jpg'),
  'womens-dresses': require('./womens-dresses.jpg'),
  'womens-jewellery': require('./womens-jewellery.jpg'),
  'womens-shoes': require('./womens-shoes.jpg'),
  'womens-watches': require('./womens-watches.jpg'),
};
